= Lacewing's Collection of Memes
Lacewing <lacy.lacewing@gmail.com>
0.1.1, {docdate}: An Actually Readable README
include::src/header.adoc[tags=common]
include::src/license.adoc[tags=attrs]
include::src/github.adoc[tags=attrs]
:description: README for Lacewing's collection of memes.
:keywords: meme

[abstract]
== Introduction
Lacewing's Collection of Memes contains memes created and/or collected by Lacewing and possibly others. Besides obvious functionalities, it can be a playground for practicing document writing and/or typsetting skills.

== Usage
You'll have to download the files and preview/convert them, because GitHub's AsciiDoc rendering lacks many features.

*`asciidoctor`* is the `AsciiDoc` processoer for this project.

=== Get Files

include::src/github.adoc[tags=get-repo-en]

=== Styling
`HTML` supports customization, so does `AsciiDoc` since it converts to `HTML`. Feel free to apply your own style sheets and even scripts.

Some converters also support styling `PDF` output.

=== Converting
Here are some suggestions for getting memeable output.

First, convert `AsciiDoc` to `HTML`. (For those who straightaway go to `PDF`, you nerds)

Then, you can convert it to

* images (`PNG` `JPG` etc.) by capturing screenshots of `HTML` elements (by using your browser's 'inspection' tools) or taking screenshots
* animated pictures or videos if the meme is dynamic using screen recorders
* `PDF` via browsers 'printing'

_Meme the memes!_

== Contributing

=== Pull Requests

include::src/github.adoc[tags=fork-pr-en]

=== Guidelines

==== Content

* upon editing (excluding simple typo correction and such), please add your name and optionally, email address to the "author line" or such data
* by not adding your author information, you choose not to be credited for the work
* *reuse (refer)* content and sources when possible

==== Format

* use markup languages which can be *easily converted to `HTML`*; +
	`AsciiDoc` (`.adoc`) is encouraged
* use *`asciidoctor`* for processing `AsciiDoc`
* format text reasonably, make it *easy to read and edit*
* check spelling and grammar, also punctuation and typesetting

==== File Management

* use *flat* folder structure, meaning no creating lower-level folder; *`.` indicates 'folder'*, +
	e.g. `general.punchline.adoc` for `general/punchline.adoc`
* use lowercase, with *`-` replacing white spaces*, +
	e.g. `calamity-mod` for "Calamity Mod"
* follow special naming rules, +
	e.g. `README.adoc` and `LICENSE`
* viewable content in `content/`, name after *full names*
* sources and *reusable parts* in `src/`, name after *abbreviations*
* images, *excluding icons*, in `images/`, name after *abbreviations*
* *icon images* in `images/icons/`, name after *full names*
* audios in `audios/`, video in `videos/`, both name after *abbreviations*
* styles (`CSS`, etc.) in `styles/`, name after *full names*

==== Frequency

* small typo PRs are unlikely to be merged
* combine updates into 1 or a few PRs if you have a bunch of them

== Licensing
include::src/license.adoc[tags=note-en]

.{link-cc-by-deed}[{cc-by-name} Deed]
****
include::src/license.adoc[tags=deed-en]
****

Refer to the link:LICENSE[license] for more details.

[bibliography%untitled]
